Algoritmo "MEDIDAS"


Var

a, b, c, quadrado, triangulo, trapezio: real

Inicio

escreva("ESCREVA A MEDIDA A: ")
leia(a)
escreva("ESCREVA A MEDIDA B: ")
leia(b)
escreva("ESCREVA A MEDIDA C: ")
leia(c)

quadrado <- exp(a,2)
triangulo <- (a*b)/2
trapezio <- ((a+b)*c)/2

escreval
escreval("AREA DO QUADRADAO: ", quadrado:8:4)
escreval("AREA DO TRIANGULO: ", triangulo:8:4)
escreval("AREA DO TRAPEZIO: ", trapezio:8:4)


Fimalgoritmo